//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.18 at 09:52:22 AM EST 
//


package fileMapper.data.datavo.vdo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Map complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Map">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MAP_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SOURCE_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DESCR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ELEMENTS" type="{http://www.fsu.edu/data/datavo/vdo/}Map_Element" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Map", propOrder = {
    "mapid",
    "sourceid",
    "descr",
    "elements"
})
public class Map {

    @XmlElement(name = "MAP_ID", required = true)
    protected String mapid;
    @XmlElement(name = "SOURCE_ID", required = true)
    protected String sourceid;
    @XmlElement(name = "DESCR", required = true)
    protected String descr;
    @XmlElement(name = "ELEMENTS")
    protected List<MapElement> elements;

    /**
     * Gets the value of the mapid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAPID() {
        return mapid;
    }

    /**
     * Sets the value of the mapid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAPID(String value) {
        this.mapid = value;
    }

    /**
     * Gets the value of the sourceid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOURCEID() {
        return sourceid;
    }

    /**
     * Sets the value of the sourceid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOURCEID(String value) {
        this.sourceid = value;
    }

    /**
     * Gets the value of the descr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCR() {
        return descr;
    }

    /**
     * Sets the value of the descr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCR(String value) {
        this.descr = value;
    }

    /**
     * Gets the value of the elements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getELEMENTS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MapElement }
     * 
     * 
     */
    public List<MapElement> getELEMENTS() {
        if (elements == null) {
            elements = new ArrayList<MapElement>();
        }
        return this.elements;
    }

}
